swagger: '2.0'
info:
  description: HTL Programming Homework
  version: 1.0.0
  title: Address Book
basePath: /api
paths:
  /contacts:
    post:
      summary: Adds a new person to the list of contacts
      operationId: addPerson
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Person to add
          required: true
          schema:
            $ref: '#/definitions/Person'
      responses:
        '201':
          description: Person successfully created
          schema:
            type: object
            $ref: '#/definitions/Person'
        '400':
          description: Invalid input (e.g. required field missing or empty)
    get:
      summary: Get all persons in contact list
      operationId: getAllPersons
      produces:
        - application/json
      responses:
        '200':
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Person'
  '/contacts/{personId}':
    delete:
      summary: Deletes a person from the list of contacts
      operationId: deletePerson
      produces:
        - application/json
      parameters:
        - name: personId
          in: path
          description: ID of person to delete
          required: true
          type: integer
          format: int32
      responses:
        '204':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Person not found
definitions:
  Person:
    type: object
    required:
      - id
      - email
    properties:
      id:
        type: integer
        format: int32
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
